  backend:
    container_name: springboot
    build:
      context: ./STUDENTAPI-SPRINGBOOT
      dockerfile: ../STUDENTAPI-FULLSTACK/backend.Dockerfile
    image: dockeraws-backend:latest
    ports:
      - "2001:2000"
    depends_on:
      mysqldb:
        condition: service_healthy
    restart: on-failure
    networks:
      - springboot-react-network

  frontend:
    container_name: react
    build:
      context: ./STUDENTAPI-REACT
      dockerfile: ../STUDENTAPI-FULLSTACK/frontend.Dockerfile
    image: dockeraws-frontend:latest
    ports:
      - "3001:80"
    depends_on:
      backend
    networks:
      - springboot-react-network
